### ISSUE TITLE
Week 3 - Review Ticket 

### ISSUE THREAD

**Issue by iBraskyy** [yeonjoonhong/m22-p1-mortmons#15]
**Scrum Master(Ryan)**
Overview of progress with readme: [read me](https://github.com/yeonjoonhong/m22-p1-mortmons#readme)
Tickets (scrumboard): [GitHub scrum board](https://github.com/yeonjoonhong/m22-p1-mortmons/projects/1) 
Expected backlog post break: [Scrum board -post winter backlog](https://github.com/yeonjoonhong/m22-p1-mortmons/projects/1#column-17243043)
wiki : [wiki](https://github.com/yeonjoonhong/m22-p1-mortmons/wiki)
**individual section(week 3 and EC)**
[individual section Ryan (week 3 FRQ & EC)](https://docs.google.com/document/d/1Pm_XrxU1n_ImfJ6rc1D8SJvzATNrfFgx70cYqqWeWQ4/edit?usp=sharing)
**Grading(Ryan)**
_Team: 3.5/5 (-1 for Database, -0.5 for deployment)_
_Individual 1/2 + 2 extra credit (completion of FRQ 3 without input deployment + completion of practice exam)_
_**Total: 6.5/7**_

**Design Manager(Rohan)** 
_Note: We don't have the site deployed, which is why there aren't any links to runtime, but we showed pages during live review Friday._
Layout: https://github.com/yeonjoonhong/m22-p1-mortmons/blob/main/src/main/resources/templates/layout.html
Screen 1(food api): [frontend](https://github.com/yeonjoonhong/m22-p1-mortmons/blob/main/src/main/resources/templates/recipeapi.html) ; [backend](https://github.com/yeonjoonhong/m22-p1-mortmons/blob/main/src/main/java/com/nighthawk/csa/recipeapi.java)
Screen 2(bmi calculator): [frontend](https://github.com/yeonjoonhong/m22-p1-mortmons/blob/main/src/main/resources/templates/bmicalc.html)
Screen 3(fitness quiz): [frontend](https://github.com/yeonjoonhong/m22-p1-mortmons/blob/main/src/main/resources/templates/quiz.html)
**Individual Section(Rohan)** 
FRQ 2: [controller](https://github.com/yeonjoonhong/m22-p1-mortmons/blob/main/src/main/java/com/nighthawk/csa/Lightcontroller.java) + [java](https://github.com/yeonjoonhong/m22-p1-mortmons/blob/main/src/main/java/com/nighthawk/csa/Lightfrq.java) ; [frontend](https://github.com/yeonjoonhong/m22-p1-mortmons/blob/main/src/main/resources/templates/light.html)
FRQ 3 and Practice Exam EC: [code/answers](https://docs.google.com/document/d/12qY_mZik7xg62Tva7lyQsT8DuVXNeKzJz-Af2-3ytEc/edit)(w/ review comments) ; [frontend w/ javascript for FRQ 3](https://github.com/yeonjoonhong/m22-p1-mortmons/blob/main/src/main/resources/templates/square.html)
_Note 2: Worked together with group on Practice Exam_
**Grading(Rohan)**
_Team: 3.5/5 (-1 for Database, -0.5 for deployment)_
_Individual 1.5/2 + 2 extra credit (completion and deployment of FRQ 2 + completion of FRQ 3 w/out input deployment + completion of practice exam)_
_**Total: 7/7**_

**Technical officer(Dhruv)** tangibles
Database with CRUD:
Runtime <link to CRUD page runtime>
View <link to JavaScript fetch>
Control <link to control>
Model SQL <link to sql crud>
Model JPA <link to jpa queries>
(Technical Officer wasn't able to get database running, or model JPA.)
Individual (Dhruv)_
FRQ 2: (http://localhost:8080/aboutDhruv)
FRQ 3: (http://localhost:8080/aboutDhruv)
Pratice exam (https://docs.google.com/document/d/1X7XyFS4PlT2w3KYIvdxhBM3LlpO7YHtCpnGhUD08JEg/edit#)
Total Score: 
3.5/5 for team section (-1 for Database, -0.5 for deployment)
Dhruv Individual: 1/2, for completing FRQs, but not being able to deploy successfully. +2 extra credit for practice exam. Total score 6.5/7

**Deployment manager(Samuel)** tangibles
Update procedure: <link to deployment guid that contains procedure for someone to make an update to deployment>
Nginx config: <link to deployment guide containing paste of configuration file>
Service config: <link to deployment guide containing paste of service file>
**NOTE: Mr. mort after you let me use the microusb for my pi to restart, i came home that day only to find my pi won't turn on so now my group no longer has a person with a rasp pi**
_Team: 3.5/5 (-1 for Database, -0.5 for deployment)_
_Individual 1.5/2 + 2 extra credit (completion and deployment of FRQ 2 + completion of FRQ 3 w/out input deployment + completion of practice exam)_
[FRQ 2 & 3 html](https://github.com/yeonjoonhong/m22-p1-mortmons/blob/main/src/main/resources/templates/SAMFRQs.html)
[Practice exam Extra Cred](https://docs.google.com/document/d/1O-a35d8e3JJJLawD2xLoSM-uPpG3gG1AbvbofjUwLE8/edit?usp=sharing)
_**Total: 7/7**_

**GitHub admin (Yeonjoon)** tangibles
Commit, pull request procedure <https://github.com/yeonjoonhong/m22-p1-mortmons/blob/main/docs/contributing.md>
Branching procedure <https://github.com/yeonjoonhong/m22-p1-mortmons/blob/main/docs/contributing.md>

Team Grade: 3.5/5 (Database -1, Deployment -0.5)
Individual Grade: 1.75/2 **+ 2 extra credit points** (completed FRQ 2 and 3 and deployed it onto the website. Commits and added many features for website{html, navbar bootstrap conflict fix, etc.})
Commits: https://github.com/yeonjoonhong/m22-p1-mortmons/commits?author=yeonjoonhong
Commit Graphs: https://github.com/yeonjoonhong/m22-p1-mortmons/graphs/contributors

> - FRQ 2, FRQ 3 - http://localhost:8080/CB%20FRQ (link on the website) | Gist links: [Unit 2](https://gist.github.com/yeonjoonhong/0667b5913ec60fd4f671393bcbad8d18), [Unit 3](https://gist.github.com/yeonjoonhong/75ab299171abf1fe234b282b18c00853)
> - Extra Credit FRQ - http://localhost:8080/CB%20FRQ (link on the website) | Link: [EC FRQ](https://docs.google.com/document/d/1kTaCamzeitbRCEy8XAVSzHs51U2em4JG59lDQ4ghDfs/edit)

**Total: 7.25/7**

**Comment by jm1021** [comment]
FRQ3 by Ryan needs to be in IDE as I can see many errors by looking at it.  Rohan has very nice start on his FRQ2, if I could see this running somewhere this would be "excellence".  Sam, I am very concerned about 1.5/2 on the FRQs, perhaps a 1/2; there is no attempt to do what Rohan is doing.  Dhruv, pointing to localhost assume that I ran your project.   I did run it and I was impressed to see a bunch of ideas on pages (seems like it came from Yeonjoon who did not score himself.  

I am glad to see you doing extra credit.  I will give you all 6.5/7.  But, honestly your team seems individually focused and point centric.   The only thing I see in the project that is good... Rohan's work on FRQ2 and Yeonjoon's proliferation of idea on page.  Everything else just seems hail mary point focussed.
